source "https://supermarket.chef.io"

cookbook 'ruby_build'
cookbook 'rbenv', github: "fnichol/chef-rbenv"
cookbook 'nginx', "2.7.6"
cookbook 'mysql', "6.1.0"
cookbook 'git'
cookbook 'zsh'
cookbook 'vim'
cookbook 'tmux'
cookbook 'ntp'
cookbook 'nodebrew'
cookbook 'timezone-ii'
cookbook 'libmysqlclient'
cookbook 'graphviz'
cookbook 'imagemagick'
